name: Bug Report
description: Report an issue with Lara Verifactu
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar un bug. Por favor completa la siguiente información.

  - type: textarea
    id: description
    attributes:
      label: Descripción del Bug
      description: Una descripción clara y concisa del bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Pasos para Reproducir
      description: Pasos para reproducir el comportamiento.
      placeholder: |
        1. Ir a '...'
        2. Hacer clic en '...'
        3. Scroll down to '...'
        4. Ver error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento Esperado
      description: Una descripción clara de lo que esperabas que sucediera.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento Actual
      description: Una descripción clara de lo que realmente sucede.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Entorno
      description: |
        Proporciona información sobre tu entorno.
      value: |
        - PHP Version:
        - Laravel Version:
        - Lara Verifactu Version:
        - OS:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs Relevantes
      description: Por favor copia y pega cualquier log relevante.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Información Adicional
      description: Añade cualquier otro contexto sobre el problema aquí.

