name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.3, 8.4]
        laravel: [12.*, 13.*]
        stability: [prefer-stable]
        db: [mariadb, mysql]
        include:
          - laravel: 12.*
            testbench: 10.*
            carbon: ^3.0
          - laravel: 13.*
            testbench: 11.*
            carbon: ^3.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.db }} - ${{ matrix.stability }}

    services:
      db:
        image: ${{ matrix.db == 'mysql' && 'mysql:8.4' || 'mariadb:12.3' }}
        env:
          MARIADB_DATABASE: verifactu_test
          MARIADB_USER: verifactu
          MARIADB_PASSWORD: secret
          MARIADB_ROOT_PASSWORD: root
          MYSQL_DATABASE: verifactu_test
          MYSQL_USER: verifactu
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="${{ matrix.db == 'mysql' && 'mysqladmin' || 'mariadb-admin' }} ping -h 127.0.0.1 -uroot -proot --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    env:
      DB_DRIVER: ${{ matrix.db }}
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: verifactu_test
      DB_USERNAME: verifactu
      DB_PASSWORD: secret

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, pdo_mysql, soap, openssl
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "nesbot/carbon:${{ matrix.carbon }}" --dev --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest --ci

